image: rambabusaravanan/firebase

stages:
  - deploy

cache:
  paths:
    - TestTool/node_modules/
  key: "$CI_BUILD_REPO"

deploy-prod:
  stage: deploy
  only:
    - develop
  script:
    - cd TestTool
    - yarn
    - yarn run build:prod
    - firebase use fitapp-test-tool --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
